Grupo\ProjetoBundle\Entity\Relatos:
  type: entity
  table: relatos
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    novoRelato:
      type: text
      length: 2550
      unique: false
      required: true
    pais:
      type: string
      length: 20
      unique: false
      required: true
    cidade:
      type: string
      length: 20
      unique: false
      required: true
    autor:
      type: string
      lenght: 20
      unique: false
      required: true
    data:
      type: date
      required: true
 
